[build]
  functions = "functions"

[[redirects]]
  from = "/api/verify-token.json?*"
  to = "/api/verify-token.json?*"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[images]
remote_images = [
  "https?://astro\\.build/.*"
]

[[headers]]
for = "/assets/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[context]

  [context.production]

    [context.production.images]
    remote_images = [
      "https?://astro\\.build/.*"
    ]

    [[context.production.headers]]
    for = "/assets/*"

      [context.production.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  [context.main]

    [context.main.images]
    remote_images = [
      "https?://astro\\.build/.*"
    ]

    [[context.main.headers]]
    for = "/assets/*"

      [context.main.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"